# -*- coding: utf-8 -*-
"""EDA Flight Delay Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdWGTjNlBNzPPe68OhIFvcSQPcKGaTGF
"""

import streamlit as st
import pandas as pd

# Title and Intro
st.title("Flight Delay Prediction – Exploratory Data Analysis")
st.markdown("""
**The art of story telling:** Diving into basic data overview, missing values, univariate analysis, bivariate analysis, categorical and numerical relationship.
""")

st.header("1. Shape")
st.subheader("(6489062, 26)")
st.write("""
The data is available at DOT's Bureau of Transportation Statistics, an official website of US Government.
There are 25 features and one target column (binary class).
The features are related to congestion, time of departure, aircraft, crews and weather.
""")

#====================================================================================

st.header("2. Feature Information")

# Create schema as a dictionary
schema = {
    "Features": [
        "MONTH", "DAY_OF_WEEK", "DEP_DEL15", "DEP_TIME_BLK", "DISTANCE_GROUP",
        "SEGMENT_NUMBER", "CONCURRENT_FLIGHTS", "NUMBER_OF_SEATS", "CARRIER_NAME",
        "AIRPORT_FLIGHTS_MONTH", "AIRLINE_FLIGHTS_MONTH", "AIRLINE_AIRPORT_FLIGHTS_MONTH",
        "AVG_MONTHLY_PASS_AIRPORT", "AVG_MONTHLY_PASS_AIRLINE", "FLT_ATTENDANTS_PER_PASS",
        "GROUND_SERV_PER_PASS", "PLANE_AGE", "DEPARTING_AIRPORT", "LATITUDE", "LONGITUDE",
        "PREVIOUS_AIRPORT", "PRCP", "SNOW", "SNWD", "TMAX", "AWND"
    ],
    "Data type": [
        "int64", "int64", "int64", "object", "int64",
        "int64", "int64", "int64", "object",
        "int64", "int64", "int64",
        "int64", "int64", "float64",
        "float64", "int64", "object", "float64", "float64",
        "object", "float64", "float64", "float64", "float64", "float64"
    ]
}

# Convert into DataFrame
f_info_df = pd.DataFrame(schema)
st.dataframe(f_info_df)
st.write("""
The 'object' type features need special attention while modelling for better compatibility with algorithms.
""")

#====================================================================================

st.header("3. Description of non-numeric features")

# Data for the table
data = {
    "DEP_TIME_BLK": ["6489062", "19", "0800-0859", "452391"],
    "CARRIER_NAME": ["6489062", "17", "Southwest Airlines Co.", "1296329"],
    "DEPARTING_AIRPORT": ["6489062", "96", "Atlanta Municipal", "392603"],
    "PREVIOUS_AIRPORT": ["6489062", "356", "NONE", "1449009"]
}

index = ["count", "unique", "top", "freq"]

# Create DataFrame
describe_non_numeric_df = pd.DataFrame(data, index=index)
st.table(describe_non_numeric_df)
st.write("""
This indicates rush hour as 8-9 AM and Southwest Airlines Co. as the most sought airlines.
""")

#====================================================================================

st.header("4. Distribution of non-numerical features")
st.image("charts/non numeric distribution .png")
st.write("""
The y-axis of each plot is number of flight records and x-axis is the respective categorical values.
Airlines and airports should focus resources and staff on peak daytime hours, as that’s when congestion and delay risk are highest.
Operational planning and delay mitigation efforts should prioritize high-volume carriers, as improving their reliability impacts the largest number of customers.
The highest-traffic airports are key nodes; investments in infrastructure or efficiency improvements here yield the biggest improvements in overall system performance and delay reduction.
""")

#====================================================================================

st.header("5. Distribution of numerical features")
st.image("charts/Unique Values per Numeric Feature.png")
st.write("""
This graph shows the spread of each numeric features.
Congestion related features have the highest values.
""")

#====================================================================================
st.header("6. Detailed distribution of numeric features")
st.image("charts/Distribution of Numerical Features.png")
st.write("""
This presents the range and variation of unique bins/ values of each individual numeric feature in more details.
The y-axis of every plot is number of flight records and x-axis is the respective values.
""")

#====================================================================================

st.header("7. Missing values indicator")
st.image("charts/missing values.png")
st.write("""
The y-axis is number of flight records and x-axis represents the columns of the dataframe.
Presence of white colour indicates missing values.
Here the plot is completely black signalling no missing values in the dataset and Data Completeness.
This ensures high data quality and reliability for modeling and business decisions.

""")


#====================================================================================

st.header("8. Correlation Matrix")
st.image("charts/correlation.png")
st.write("""
Darker shades points to higher correlation between two features.
Only some features show strong relationships with one another, which can inform feature selection—these correlations might indicate operational dependencies or shared drivers of delay risk (e.g., flights vs. airport traffic, passenger volume, time).
Invisible or pale blocks mean those feature pairs don’t move together and don’t duplicate information, these features add value in your model by bringing in independent signals that might help catch rare delay drivers.
""")

#====================================================================================


st.header("9. Percentage of flights- Monthwise")

monthly_flights = {
    "Month": [8, 7, 10, 5, 6, 3, 12, 4, 11, 9, 1, 2],
    "Percentage of flights": [8.93, 8.90, 8.65, 8.60, 8.58, 8.53, 8.50, 8.22, 8.19, 8.16, 7.73, 6.95]
}

# Convert to DataFrame
monthly_flights_df = pd.DataFrame(monthly_flights)

# Replace month number with month name
monthly_flights_df["Month"] = pd.to_datetime(monthly_flights_df["Month"], format="%m").dt.strftime("%B")

st.dataframe(monthly_flights_df)
st.write("""
This indicates that tighter schedules and shorter turnaround times may increase the risk of delays.
""")

st.write("""
By identifying months with the highest percentage of flights, businesses can align promotional campaigns,
maintenance schedules, and contingency planning with demand cycles, capturing revenue opportunities and reducing risk during peak travel periods.
Here every month has almost similar number, so every decision w.r.t. peak months remain same.
""")

#====================================================================================

st.header("10. Percentage of flights- Day of the week")

data = {
    "Day": [5, 1, 4, 2, 3, 7, 6],
    "Percentage of flights": [14.93, 14.90, 14.72, 14.58, 14.45, 14.21, 12.17]
}

# Convert to DataFrame
dow_df = pd.DataFrame(data)

# Map numbers to weekday names (1 = Sunday)
day_map = {
    1: "Sunday",
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday",
    7: "Saturday"
}
dow_df["Day"] = dow_df["Day"].map(day_map)

# Show as a table in Streamlit
st.dataframe(dow_df)

st.write("""
Week specific planning also remain same, only Friday has slightly less traffic.
""")

#===================================================================================================

st.header("11. Flight counts by part of the day")
st.image("charts/Flight counts by part of day.png")
st.write("""
The air traffic reduces as the day comes to an end. Late night and early morning slots are comparatively vacant.
The authorities can reduce ground crews and ATC staffs.
This allows various maintenance tasks related to infrastructure and passenger services, and free movement of cargo aircrafts and VIPs.
""")

#===================================================================================================

st.header("12. Heatmap of Average Delay Rate by Time Part of Day and Day of Week")
st.image("charts/DOW_part of day vs delay.png")
st.write("""
Day-to-day differences are minimal—time of day matters more than day of week for predicting delays.
Early morning slots remain the most reliable for on-time departures, suitable for premium scheduling or critical operations.
""")

#===================================================================================================

st.header("13. Percentage of flights- for different seasons")

data = {
    "Season": ["Summer", "Spring", "Fall", "Winter"],
    "Percentage of flights": [26.42, 25.36, 25.01, 23.19]
}

seasons_df = pd.DataFrame(data)

st.dataframe(seasons_df)

st.write("""
The distribution shows that flight operations are highest in Summer and Spring, reflecting peak travel demand,
likely driven by vacations, holidays, and favorable weather conditions.
Target peak operational efficiency during Summer and Spring, while maintaining robust contingency plans for Winter to ensure smooth flight operations and minimize delays.
""")

#===================================================================================================
st.header("14. Percentage of Flights per company")
st.image("charts/flights per company.png")
st.write("""
The chart highlights which airlines drive the bulk of U.S. flight operations and helps businesses prioritize collaboration, market strategy, and operational focus accordingly.
""")

#===================================================================================================

st.header("15. Proportion of Delayed & Non-Delayed Flights")
st.image("charts/delay proportion.png")
st.write("""
The distribution in our target variable is about 81% in class 0 (false), and 19% in class 1 (true).
Imbalanced target class in flight delay prediction require targeted modeling strategies
""")

#===================================================================================================

st.header("16. Delay vs Congestion Features")

data = {
    "DEP_DEL15": [0, 1],
    "CONCURRENT_FLIGHTS": [27.75, 28.23],
    "NUMBER_OF_SEATS": [133.47, 134.88],
    "AIRPORT_FLIGHTS_MONTH": [12575.67, 13171.57],
    "AIRLINE_FLIGHTS_MONTH": [62952.37, 63221.12],
    "AVG_MONTHLY_PASS_AIRPORT": [1575960.45, 1645056.70],
    "AVG_MONTHLY_PASS_AIRLINE": [7818546.94, 7829133.02]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Set DEP_DEL15 as index (like in your input table)
df.set_index("DEP_DEL15", inplace=True)

st.dataframe(df, use_container_width=True)  # auto adjust width

st.write("""
Congestion is the real villian.
Delayed flights consistently see higher averages for concurrent flights, seats, airport flights, and passenger volumes compared to on-time flights.
Busy environments (more flights, passengers, and seats) increase the likelihood of departure delays.
""")

#===================================================================================================


st.header("17. Concurrent Flights vs. Airport Flights")
st.image("charts/concurrent vs AP flights.png")
st.write("""

As airport and scheduling congestion grows, delay likelihood increases,
requiring targeted congestion management and proactive operational planning to minimize disruptions and deliver reliable service.
""")

#===================================================================================================

st.header("18. Segment Number Across Distance Groups")
st.image("charts/segment number across distance groups.png")
st.write("""
Across in all distance groups, delayed flights (red) tend to occur in later segments of the aircraft’s operational cycle compared to on-time flights (green).
This means delay risk builds up across the day as planes make multiple trips, especially on shorter-distance routes.
This is termed as 'Delay Propogation'
""")

#===================================================================================================

st.header("19. Delay vs Weather Features")

# Data
data = {
    "DEP_DEL15": [0, 1],
    "AWND": [8.25, 8.72],
    "PRCP": [0.09, 0.16],
    "SNOW": [0.02, 0.06],
    "SNWD": [0.08, 0.13],
    "TMAX": [71.54, 71.12]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Set DEP_DEL15 as index (to match your table style)
df.set_index("DEP_DEL15", inplace=True)

st.dataframe(df)

st.write("""
Weather conditions—especially wind, precipitation, and snow are clearly worse for delayed departures.
This supports investing in weather-responsive operations (staffing, de-icing, ground logistics) to reduce delays.
The difference in averages is small since most days/locations see mild weather (most values close to zero), but spikes in these factors coincide with higher delay risk.
""")

#===================================================================================================
st.header("20. Wind Speed Distribution")
st.image("charts/Wind speed vs delay.png")
st.write("""
The KDE plot shows how wind speed varies for on-time vs. delayed flights. Both distributions peak around 7–9m/s,
but delayed flights slightly skew right, indicating that higher wind speeds are associated with a greater likelihood of delays.
""")

#===================================================================================================
st.header("21. Maximum Temperature Across Months")
st.image("charts/Temperature vs Delay.png")
st.write("""
Maximum temperature varies seasonally, but does not differentiate delayed flights from on-time ones.
Temperature, by itself, is not a key driver of flight delays,focus on other operational or weather features when assessing risk.
""")

#===================================================================================================


st.header("22. Plane Age vs Percentage of Delayed Flights")
st.image("charts/Plane age vs delay.png")
st.write("""
No strong trend observed, age of plane is not critical to flight delay.
""")

#===================================================================================================
